server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://45.149.156.219:3306/c_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1350932647
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    port: 6379
    host: 200.229.17.47
    password: S1350932647
    database: 4


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
